Add SUSE support

diff --git a/install_prereq b/install_prereq
--- a/install_prereq
+++ b/install_prereq
@@ -9,13 +9,13 @@
 set -e
 
 usage() {
-	echo "$0: a script to install distribution-specific prerequirement"
-	echo 'Revision: $Id$'
-	echo ""
-	echo "Usage: $0:                    Shows this message."
-	echo "Usage: $0 test                Prints commands it is about to run."
-	echo "Usage: $0 install             Really install."
-	echo "Usage: $0 install-unpackaged  Really install unpackaged requirements."
+  echo "$0: a script to install distribution-specific prerequirement"
+  echo 'Revision: $Id$'
+  echo ""
+  echo "Usage: $0:                    Shows this message."
+  echo "Usage: $0 test                Prints commands it is about to run."
+  echo "Usage: $0 install             Really install."
+  echo "Usage: $0 install-unpackaged  Really install unpackaged requirements."
 }
 
 # Basic build system:
@@ -27,54 +27,40 @@ PACKAGES_DEBIAN="$PACKAGES_DEBIAN libcurl-dev libspeex-dev libspeexdsp-dev libog
 PACKAGES_DEBIAN="$PACKAGES_DEBIAN libpq-dev unixodbc-dev libsqlite0-dev libmysqlclient15-dev libneon27-dev libgmime-dev libusb-dev liblua5.1-0-dev lua5.1"
 PACKAGES_DEBIAN="$PACKAGES_DEBIAN libopenh323-dev libvpb-dev libgtk2.0-dev libmysqlclient-dev libbluetooth-dev libradiusclient-ng-dev freetds-dev"
 PACKAGES_DEBIAN="$PACKAGES_DEBIAN libsnmp-dev libiksemel-dev libcorosync-dev libnewt-dev libpopt-dev libical-dev libspandsp-dev libjack-dev"
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN libresample-dev libc-client-dev binutils-dev libsrtp-dev libgsm1-dev libedit-dev doxygen libjansson-dev libldap-dev"
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN subversion git libxslt1-dev automake libsrtp-dev libncurses5-dev python-dev"
-PACKAGES_RH="automake bzip2 gcc gcc-c++ patch ncurses-devel openssl-devel libxml2-devel unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel"
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN libresample-dev libc-client-dev binutils-dev libsrtp-dev libgsm1-dev libedit-dev libldap-dev"
+PACKAGES_RH="automake gcc gcc-c++ ncurses-devel openssl-devel libxml2-devel unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel"
 PACKAGES_RH="$PACKAGES_RH spandsp-devel freetds-devel net-snmp-devel iksemel-devel corosynclib-devel newt-devel popt-devel libtool-ltdl-devel lua-devel"
 PACKAGES_RH="$PACKAGES_RH sqlite-devel libsqlite3x-devel radiusclient-ng-devel portaudio-devel postgresql-devel libresample-devel neon-devel libical-devel"
 PACKAGES_RH="$PACKAGES_RH openldap-devel gmime22-devel sqlite2-devel mysql-devel bluez-libs-devel jack-audio-connection-kit-devel gsm-devel libedit-devel libuuid-devel"
-PACKAGES_RH="$PACKAGES_RH jansson-devel libsrtp-devel pjproject-devel subversion git libxslt-devel python-devel"
+PACKAGES_SUSE="automake gcc gcc-c++ ncurses-devel libopenssl-devel libxml2-devel unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel"
+PACKAGES_SUSE="$PACKAGES_SUSE spandsp-devel freetds-devel net-snmp-devel iksemel-devel libcorosync-devel newt-devel popt-devel libtool-ltdl-devel lua-devel"
+PACKAGES_SUSE="$PACKAGES_SUSE sqlite3-devel radiusclient-ng-devel portaudio-devel postgresql-devel libneon-devel libical-devel"
+PACKAGES_SUSE="$PACKAGES_SUSE openldap2-devel gmime-devel libmysqld-devel libmysqld-devel bluez-devel pulseaudio-module-jack libgsm-devel libedit-devel libuuid-devel"
 
-PACKAGES_OBSD="popt gmake wget libxml libogg libvorbis curl iksemel spandsp speex iodbc freetds-0.63p1-msdblib mysql-client gmime sqlite sqlite3 jack libxslt"
-PACKAGES_FBSD="autoconf gcc binutils popt gmake wget libxml2 libogg libvorbis curl iksemel spandsp speex unixODBC freetds-devel mysql55-client gmime2 sqlite"
-PACKAGES_FBSD="$PACKAGES_FBSD sqlite3 libxslt jansson e2fsprogs-libuuid gsm libsrtp libsamplerate"
+PACKAGES_OBSD="popt gmake wget libxml libogg libvorbis curl iksemel spandsp speex iodbc freetds-0.63p1-msdblib mysql-client gmime sqlite sqlite3 jack"
 
 KVERS=`uname -r`
 
-JANSSON_VER=2.4
-
 case "$1" in
-test)
-	testcmd=echo
-	;;
-install)
-	testcmd=''
-	;;
-install-unpackaged)
-	unpackaged="yes"
-	;;
-'')
-	usage
-	exit 0
-	;;
-*)
-	usage
-	exit 1
-	;;
+test)    testcmd=echo ;;
+install) testcmd='' ;;
+install-unpackaged) unpackaged="yes" ;;
+'') usage; exit 0 ;;
+*) usage; exit 1 ;;
 esac
 
 in_test_mode() {
-	test "$testcmd" != ''
+  test "$testcmd" != ''
 }
 
 check_installed_debs() {
-	for pack in "$@" ; do
-		tocheck="${tocheck} ^${pack}$ ~P^${pack}$"
+	for pack in "$@"
+	do
+		tocheck="${tocheck} ^${pack}$"
 	done
-	pkgs=$(aptitude -F '%c %p' search ${tocheck} 2>/dev/null | awk '/^p/{print $2}')
-	if [ ${#pkgs} -ne 0 ]; then
-		echo $pkgs | sed -r -e "s/ ?[^ :]+:i386//g"
-	fi
+	aptitude -F '%c %p' search ${tocheck} 2>/dev/null \
+		| awk '/^p/{print $2}' \
+		| grep -v ':i386$'
 }
 
 # parsing the output of yum is close to impossible.
@@ -97,45 +83,30 @@ check_installed_pkgs() {
 	done
 }
 
-check_installed_fpkgs() {
-	for pack in "$@"
-	do
-		if [ `pkg info -a | grep $pack | wc -l` = 0 ]; then
-		echo $pack
-		fi
-	done
-}
-
 handle_debian() {
-	if ! [ -x "$(command -v aptitude)" ]; then
-		apt-get install aptitude
-	fi
+	# echo "# Distribution is Debian or compatible"
 	extra_packs=`check_installed_debs $PACKAGES_DEBIAN`
-	$testcmd aptitude update
-	if [ x"$extra_packs" != "x" ] ; then
-		$testcmd aptitude install -y $extra_packs
-	fi
+	$testcmd aptitude install -y $extra_packs
 }
 
 handle_rh() {
+	# echo "# Distribution is RedHat-based or compatible"
 	extra_packs=`check_installed_rpms $PACKAGES_RH`
-	if [ x"$extra_packs" != "x" ] ; then
-		$testcmd yum install -y $extra_packs
-	fi
+        # FIXME: is there yum with RHEL 4?
+	$testcmd yum install -y $extra_packs
+}
+
+handle_suse() {
+	# echo "# Distribution is RedHat-based or compatible"
+	extra_packs=`check_installed_rpms $PACKAGES_SUSE`
+        # FIXME: is there yum with RHEL 4?
+	$testcmd zypper install -y $extra_packs
 }
 
 handle_obsd() {
+	# echo "# Distribution is OpenBSD or compatible"
 	extra_packs=`check_installed_pkgs $PACKAGES_OBSD`
-	if [ x"$extra_packs" != "x" ] ; then
-		$testcmd pkg_add $extra_packs
-	fi
-}
-
-handle_fbsd() {
-	extra_packs=`check_installed_fpkgs $PACKAGES_FBSD`
-	if [ x"$extra_packs" != "x" ] ; then
-		$testcmd pkg install -y $extra_packs
-	fi
+	$testcmd pkg_add $extra_packs
 }
 
 install_unpackaged() {
@@ -145,59 +116,11 @@ install_unpackaged() {
 	make && make install
 	cd ..
 
-	# Only install libresample if it wasn't installed via package
-	if ! test -f /usr/include/libresample.h; then
-		echo "*** Installing libresample ***"
-		svn co http://svn.digium.com/svn/thirdparty/libresample/trunk libresample-trunk
-		cd libresample-trunk
-		./configure && make && make install
-		cd ..
-	fi
-
-	# Only install Jansson if it wasn't installed via package
-	if ! test -f /usr/include/jansson.h; then
-		echo "*** Installing jansson ***"
-		wget -O - http://www.digip.org/jansson/releases/jansson-${JANSSON_VER}.tar.gz | zcat | tar -xf -
-		cd jansson-${JANSSON_VER}
-		./configure && make all && make install
-		cd ..
-		echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local.conf
-		/sbin/ldconfig
-	fi
-
-	# Only install libsrtp if it wasn't installed via package
-	if ! test -f /usr/include/srtp/srtp.h; then
-		echo "*** Installing libsrtp ***"
-		if [ ! -d libsrtp ]; then
-			git clone https://github.com/cisco/libsrtp.git
-			cd libsrtp
-		else
-			cd libsrtp
-			git pull
-		fi
-		git checkout "1_5_x_throttle"
-		./configure --disable-debug --disable-stdout --enable-openssl
-		make shared_library uninstall install
-		cd ..
-		echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local.conf
-		/sbin/ldconfig
-	fi
-
-	# Only install pjproject if it wasn't installed via package
-	if ! test -f /usr/include/pjlib.h; then
-		echo "*** Installing pjproject ***"
-		if [ ! -d pjproject ]; then
-			git clone https://github.com/asterisk/pjproject.git
-			cd pjproject
-		else
-			cd pjproject
-			git pull
-		fi
-		./configure CFLAGS="-DNDEBUG -DPJ_HAS_IPV6=1" --enable-shared --with-external-speex --with-external-gsm --with-external-srtp --disable-sound --disable-resample && make && make install
-		cd ..
-		echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local.conf
-		/sbin/ldconfig
-	fi
+	echo "*** Installing libresample ***"
+	svn co http://svn.digium.com/svn/thirdparty/libresample/trunk libresample-trunk
+	cd libresample-trunk
+	./configure && make && make install
+	cd ..
 }
 
 if in_test_mode; then
@@ -214,45 +137,46 @@ OS=`uname -s`
 unsupported_distro=''
 
 # A number of distributions we don't (yet?) support.
-if [ "$OS" != 'Linux' -a "$OS" != 'OpenBSD' -a "$OS" != 'FreeBSD' ]; then
-	echo >&2 "$0: Your OS ($OS) is currently not supported. Aborting."
-	exit 1
+if [ "$OS" != 'Linux' -a "$OS" != 'OpenBSD' ]; then
+  echo >&2 "$0: Your OS ($OS) is currently not supported. Aborting."
+  exit 1
 fi
 
 if [ -f /etc/gentoo-release ]; then
-	unsupported_distro='Gentoo'
+  unsupported_distro='Gentoo'
 fi
 
 if [ -f /etc/mandrake-release ]; then
-	unsupported_distro='Mandriva'
+  unsupported_distro='Mandriva'
 fi
 
 if [ -f /etc/SuSE-release ]; then
-	unsupported_distro='SUSE'
+  #unsupported_distro='SUSE'
+  unsupported_distro=''
 fi
 
 if [ -f /etc/slackware-version ]; then
-	unsupported_distro='Slackware'
+  unsupported_distro='Slackware'
 fi
 
 if [ "$unsupported_distro" != '' ]; then
-	echo >&2 "$0: Your distribution ($unsupported_distro) is currently not supported. Aborting."
-	exit 1
+  echo >&2 "$0: Your distribution ($unsupported_distro) is currently not supported. Aborting."
+  exit 1
 fi
 
 # The distributions we do support:
 if [ -r /etc/debian_version ]; then
-	handle_debian
+  handle_debian
+elif [ -r /etc/SuSE-release ]; then
+  handle_suse
 elif [ -r /etc/redhat-release ]; then
-	handle_rh
+  handle_rh
 elif [ "$OS" = 'OpenBSD' ]; then
-	handle_obsd
-elif [ "$OS" = 'FreeBSD' ]; then
-	handle_fbsd
+  handle_obsd
 fi
 
 if ! in_test_mode; then
-	echo "#############################################"
-	echo "## $1 completed successfully"
-	echo "#############################################"
+  echo "#############################################"
+  echo "## $1 completed successfully"
+  echo "#############################################"
 fi
